# Gems
gems: [jekyll-paginate]

# Setup
title:               Soda
tagline:             'Soda for Scala'
description:         'Small libraries to speed up application development in Scala.'
url:                 https://innoave.github.io/soda
baseurl:             '/soda'
paginate:            5
permalink:           pretty

github:
  repo:            https://github.com/innoave/soda

# About/contact
author:
  name:              Harald Maida
  url:               https://github.com/haraldmaida
  email:             soda@innoave.com
