sudo: false

language: scala
scala:
  - 2.11.10
  - 2.12.1

jdk:
  - oraclejdk8

script:
  - java -version
  - sbt clean coverage test coverageReport

branches:
  only:
    - master
    - stable

notifications:
  email: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
  